language: java
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

script: 
  - mvn clean install 

#before_deploy:
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=$TRAVIS_BRANCH-v1.0.$TRAVIS_BUILD_NUMBER
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - git push -q https://$API_KEY@github.com/rackerlabs/cassandra-metrics-reporter --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $API_KEY
  file_glob: true
  file:
    - "./target/metrics-reporter-config-bundle-*-cassandra20x.jar"
  on:
    repo: rackerlabs/cassandra-metrics-reporter
    tags: false
    branch: rax-release
    jdk: oraclejdk8

notifications:
    irc: "irc.rackspace.com#metrics"
